#!/usr/bin/env python3
# =============================================================================
#  make_blank_map.py — 產生給 Nav2 用的「全空」靜態地圖
#
#  用法：
#      python3 scripts/make_blank_map.py                        # 預設：5x4 m 房間，原點置中
#      python3 scripts/make_blank_map.py --center 2.5 2.0       # 動捕原點在房間角落時
#      python3 scripts/make_blank_map.py --room 6 5 --res 0.1
#
#  輸出：maps/<name>.pgm + maps/<name>.yaml
#
#  為什麼要一張「空的」地圖，而不是乾脆不用靜態地圖：
#      Nav2 的 global_costmap 要有 static_layer 才知道「世界有多大」。
#      拿掉它得改 nav2_params.yaml、改 launch 的節點清單、改 lifecycle_manager
#      的 node_names —— 三個地方都可能改錯。換一張全空的圖只動一個路徑。
#
#  為什麼地圖要比房間大（margin）：
#      地圖外面是「未知」，而 planner 設了 allow_unknown: false，不會規劃進去。
#      飛機靠牆時，如果地圖剛好切在牆上，costmap 有一半是未知，規劃會變得很奇怪。
#      多留一圈讓邊界離飛行區遠一點。
#
#  ⚠️ 這張圖「沒有」把房間外面標成障礙物。它不是電子圍籬 ——
#     Nav2 照樣可以把目標設在房間外、margin 那一圈裡。第一次實飛時
#     目標點請自己點在房間內。
# =============================================================================

import argparse
import os

# 與 drone_nav2_apriltag 的地圖用同一組門檻（nav2 範例地圖的值）。
# 我們只寫 254（可通行）一種像素，不會落在門檻之間。
PGM_FREE = 254
OCCUPIED_THRESH = 0.65
FREE_THRESH = 0.196


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    ap = argparse.ArgumentParser(description="產生全空的 Nav2 靜態地圖")
    ap.add_argument("--name", default="lab_5x4")
    ap.add_argument("--room", nargs=2, type=float, default=[5.0, 4.0],
                    metavar=("X", "Y"),
                    help="房間在 map 座標 x、y 方向的長度（公尺）")
    ap.add_argument("--margin", type=float, default=1.0,
                    help="房間每一邊往外多留幾公尺")
    ap.add_argument("--center", nargs=2, type=float, default=[0.0, 0.0],
                    metavar=("X", "Y"),
                    help="房間中心在 map 座標的哪裡。動捕原點在房間正中央就是 0 0")
    # 0.05：模擬用 0.1，但實機目標容差要收到 0.2 m，
    # 0.1 的格子等於容差只有兩格寬，太粗。
    ap.add_argument("--res", type=float, default=0.05, help="每格幾公尺")
    ap.add_argument("--out-dir", default=os.path.join(here, "..", "maps"))
    args = ap.parse_args()

    size_x = args.room[0] + 2 * args.margin
    size_y = args.room[1] + 2 * args.margin
    w = int(round(size_x / args.res))
    h = int(round(size_y / args.res))
    # map_server 的 origin 是「左下角」那一格在 map 座標的位置
    ox = args.center[0] - size_x / 2.0
    oy = args.center[1] - size_y / 2.0

    os.makedirs(args.out_dir, exist_ok=True)
    pgm = os.path.join(args.out_dir, f"{args.name}.pgm")
    yml = os.path.join(args.out_dir, f"{args.name}.yaml")

    # P5 = 二進位灰階 PGM。只用標準函式庫寫，不需要 PIL。
    with open(pgm, "wb") as f:
        f.write(f"P5\n# generated by drone_bringup/scripts/make_blank_map.py\n"
                f"{w} {h}\n255\n".encode("ascii"))
        f.write(bytes([PGM_FREE]) * (w * h))

    with open(yml, "w", encoding="utf-8") as f:
        f.write(
            "# === 這個檔案是產生出來的，不要手改 ===\n"
            "# 來源：drone_bringup/scripts/make_blank_map.py\n"
            f"# 房間 {args.room[0]:g} x {args.room[1]:g} m，中心 ({args.center[0]:g}, "
            f"{args.center[1]:g})，每邊外擴 {args.margin:g} m\n"
            "# 全部是可通行格，沒有任何障礙物，也不是電子圍籬。\n"
            f"image: {args.name}.pgm\n"
            f"resolution: {args.res:.6f}\n"
            f"origin: [{ox:.6f}, {oy:.6f}, 0.000000]\n"
            "negate: 0\n"
            f"occupied_thresh: {OCCUPIED_THRESH}\n"
            f"free_thresh: {FREE_THRESH}\n")

    print(f"寫出 {pgm}")
    print(f"寫出 {yml}")
    print(f"  {w} x {h} 格 @ {args.res} m = {size_x:g} x {size_y:g} m")
    print(f"  涵蓋 x [{ox:+.2f}, {ox + size_x:+.2f}]  y [{oy:+.2f}, {oy + size_y:+.2f}]")


if __name__ == "__main__":
    main()
